import fs from 'node:fs';
const required=['index.html','src/mobile-phone-gold-v8.css','src/mobile-phone-gold-v8.js','src/xvs-canonical-phone-v9.js','src/mobile-interaction-stage-v9.css','src/mobile-interaction-stage-v9.js','src/xvs-human-delivery-v10.js','src/phone-stage-layout-v11.css','src/phone-controls-spacing-v12.css','src/phone-controls-spacing-v12.js','src/phone-scene-captions-v13.css','src/phone-scene-captions-v13.js'];
for(const file of required){if(!fs.existsSync(file))throw new Error(`Missing phone Gold Master asset: ${file}`)}
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('src/mobile-phone-gold-v8.css','utf8');
const js=fs.readFileSync('src/mobile-phone-gold-v8.js','utf8');
const xvs=fs.readFileSync('src/xvs-canonical-phone-v9.js','utf8');
const stageCss=fs.readFileSync('src/mobile-interaction-stage-v9.css','utf8');
const stageJs=fs.readFileSync('src/mobile-interaction-stage-v9.js','utf8');
const human=fs.readFileSync('src/xvs-human-delivery-v10.js','utf8');
const layout=fs.readFileSync('src/phone-stage-layout-v11.css','utf8');
const controlsCss=fs.readFileSync('src/phone-controls-spacing-v12.css','utf8');
const controlsJs=fs.readFileSync('src/phone-controls-spacing-v12.js','utf8');
const sceneCaptionCss=fs.readFileSync('src/phone-scene-captions-v13.css','utf8');
const sceneCaptionJs=fs.readFileSync('src/phone-scene-captions-v13.js','utf8');
for(const term of required.slice(1))if(!html.includes(term.replace('src/','')))throw new Error(`Phone asset not loaded: ${term}`);
if(html.includes('phone-transport-v10'))throw new Error('Deprecated duplicate phone transport runtime is still loaded');
for(const term of ['100dvh','safe-area-inset-bottom','phoneGoldBegin','body:not(.phone-premiere-started)','visibility:hidden'])if(!css.includes(term))throw new Error(`Phone shell contract missing: ${term}`);
for(const term of ['Good morning','Good afternoon','Good evening','phone-premiere-started','nativeBegin.click','showLanding','shell.hidden=false','beginButton.disabled=false'])if(!js.includes(term))throw new Error(`Phone start or restart lifecycle missing: ${term}`);
for(const term of ["'Sonia'","'Libby'",'utterance.rate=.86','utterance.pitch=1.05',"behavior:'auto'",'frame-first'])if(!xvs.includes(term))throw new Error(`Canonical XVS or frame synchronization missing: ${term}`);
for(const term of ['#phoneInteractionStage','body.phone-interaction-open .captions','min-height:58px','phoneStageIn'])if(!stageCss.includes(term))throw new Error(`Visible interaction stage style missing: ${term}`);
for(const term of ['phoneInteractionStage','Your turn, Ed','interactionMap','awaiting-ed','replaceWith(placeholder)','visualViewport','restore()'])if(!stageJs.includes(term))throw new Error(`Visible interaction stage runtime missing: ${term}`);
for(const term of ['I want to ask you something','Can a company remember?','scriptMap','cloneUtterance'])if(!human.includes(term))throw new Error(`Humanized XVS delivery missing: ${term}`);
for(const term of ['--xen-phone-header','body.phone-premiere-started #arrival #begin','body.phone-premiere-started .chrome #voice'])if(!layout.includes(term))throw new Error(`Protected phone stage contract missing: ${term}`);
for(const term of ['#xenPhoneControls','--xen-phone-caption','.captions{position:fixed','body.xen-captions-off .captions','#xenTransport{display:none'])if(!controlsCss.includes(term))throw new Error(`Phone spacing or caption lane missing: ${term}`);
for(const term of ['xenPause','xenCaptions','speechSynthesis.pause()','speechSynthesis.resume()','releasePause','xen-hard-paused','xen-captions-off'])if(!controlsJs.includes(term))throw new Error(`Authoritative phone controls missing: ${term}`);
if(controlsJs.includes('speechSynthesis.cancel()')||controlsJs.includes('voice?.click()'))throw new Error('Pause must resume the same sentence instead of cancelling and restarting narration');
for(const term of ['phone-scene-caption-slot','position:static!important','body.xen-captions-off .phone-scene-caption-slot'])if(!sceneCaptionCss.includes(term))throw new Error(`In-flow scene caption styling missing: ${term}`);
for(const term of ['anchorMap','ensureSlot','insertAdjacentElement','slot.appendChild(captions)','MutationObserver'])if(!sceneCaptionJs.includes(term))throw new Error(`Scene-aware caption placement missing: ${term}`);
console.log('PASS reusable silent phone landing, one authoritative pause/resume controller, canonical voice, scene-aware captions, visible interactions, and protected stage zones');