import fs from 'node:fs';
const required=['index.html','src/mobile-phone-gold-v8.css','src/mobile-phone-gold-v8.js','src/xvs-canonical-phone-v9.js','src/mobile-interaction-stage-v9.css','src/mobile-interaction-stage-v9.js','src/xvs-human-delivery-v10.js','src/phone-transport-v10.css','src/phone-transport-v10.js','src/phone-stage-layout-v11.css'];
for(const file of required){if(!fs.existsSync(file))throw new Error(`Missing phone Gold Master asset: ${file}`)}
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('src/mobile-phone-gold-v8.css','utf8');
const js=fs.readFileSync('src/mobile-phone-gold-v8.js','utf8');
const xvs=fs.readFileSync('src/xvs-canonical-phone-v9.js','utf8');
const stageCss=fs.readFileSync('src/mobile-interaction-stage-v9.css','utf8');
const stageJs=fs.readFileSync('src/mobile-interaction-stage-v9.js','utf8');
const human=fs.readFileSync('src/xvs-human-delivery-v10.js','utf8');
const transportCss=fs.readFileSync('src/phone-transport-v10.css','utf8');
const transportJs=fs.readFileSync('src/phone-transport-v10.js','utf8');
const layout=fs.readFileSync('src/phone-stage-layout-v11.css','utf8');
for(const term of required.slice(1))if(!html.includes(term.replace('src/','')))throw new Error(`Phone asset not loaded: ${term}`);
for(const term of ['100dvh','safe-area-inset-bottom','phoneGoldBegin','body:not(.phone-premiere-started)','visibility:hidden'])if(!css.includes(term))throw new Error(`Phone shell contract missing: ${term}`);
for(const term of ['Good morning','Good afternoon','Good evening','phone-premiere-started','nativeBegin.click','window.scrollTo(0,0)'])if(!js.includes(term))throw new Error(`Phone start runtime missing: ${term}`);
for(const term of ["'Sonia'","'Libby'","utterance.rate=.86","utterance.pitch=1.05","behavior:'auto'","frame-first"])if(!xvs.includes(term))throw new Error(`Canonical XVS or frame synchronization missing: ${term}`);
for(const term of ['#phoneInteractionStage','bottom:calc(104px','body.phone-interaction-open .captions','min-height:58px','phoneStageIn'])if(!stageCss.includes(term))throw new Error(`Visible interaction stage style missing: ${term}`);
for(const term of ['phoneInteractionStage','Your turn, Ed','interactionMap','awaiting-ed','replaceWith(placeholder)','visualViewport','restore()'])if(!stageJs.includes(term))throw new Error(`Visible interaction stage runtime missing: ${term}`);
for(const term of ['I want to ask you something','Can a company remember?','scriptMap','cloneUtterance'])if(!human.includes(term))throw new Error(`Humanized XVS delivery missing: ${term}`);
for(const term of ['#xenTransport','phone-premiere-started','xen-paused'])if(!transportCss.includes(term))throw new Error(`Phone transport style missing: ${term}`);
for(const term of ['speechSynthesis.pause()','speechSynthesis.resume()','Pause Xen','Resume Xen'])if(!transportJs.includes(term))throw new Error(`Phone transport runtime missing: ${term}`);
for(const term of ['--xen-phone-header','body.phone-premiere-started #arrival #begin','body.phone-premiere-started .chrome #voice','max-width:calc(100vw','body.phone-premiere-started .chapter'])if(!layout.includes(term))throw new Error(`Protected phone stage contract missing: ${term}`);
console.log('PASS phone landing, canonical voice, humanized script, synchronized framing, visible interactions, compact transport, and protected non-overlapping stage zones');