const VERSION='5.0.0-cinematic';
const KEY='xei.ed.cinematic.v5';
const scenes=['arrival','memory','living','panama','bilingual','manual','teach','router','propagate','reveal','constellation','summary','mandate'];
const state=Object.assign({scene:0,memory:'',contribution:'',mandate:'',voice:true,manual:'agent',lang:'EN',answer:'',paused:false},JSON.parse(localStorage.getItem(KEY)||'{}'));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
let voice=null,utterance=null,autoTimer=null,userPauseTimer=null;
const femaleNames=['Serena','Sonia','Libby','Maisie','Kate','Stephanie','Martha','Hazel','Fiona','Moira','Tessa','Amy','Emma'];
function resolveVoice(){
 const voices=speechSynthesis?.getVoices?.()||[];
 voice=voices.find(v=>/^en-GB/i.test(v.lang)&&femaleNames.some(n=>v.name.toLowerCase().includes(n.toLowerCase())))||voices.find(v=>/^en-GB/i.test(v.lang)&&!/male|daniel|george|oliver|ryan/i.test(v.name))||null;
 document.documentElement.dataset.voice=voice?'approved':'caption-only';
 return voice;
}
const scripts={
 arrival:['Good afternoon, Ed.','I am Xen.','Darren asked me to show you something he did not originally intend to build.','This is a company learning how to come alive.'],
 memory:['Ed, can your company remember?','Not files. Not records. Not data stored somewhere.','Can it remember what you decided, why it mattered, what your best people learned, and what every future company should inherit?'],
 living:['Most software shows a company as boxes, records, and reports.','But a company is not a collection of boxes.','It is purpose moving through people, decisions, departments, systems, and time.','The first living part of Checkmate began with one new department.'],
 panama:["You created Checkmate's first real B D C department in Panama.","Darren's first problem was not how to make a manual.",'It was how to give six people operating judgment they did not yet possess.','A binder could hold information. But it could not coach, answer, translate, remember, or improve.'],
 bilingual:['We did not translate one document.','We built one operating standard that could live in two languages without losing its meaning.','The same customer promise. The same coaching logic. The same operating intent.'],
 manual:['Let me walk you through what the agent sees.','The agent does not leave the work to search for knowledge.','The knowledge comes into the work.','This is not a PDF with buttons. It is an operating surface.'],
 teach:['But this is where the system becomes a Living Company.','When a customer says, I am just looking, what should every future representative understand or do?','Tell me in your own words.'],
 router:['I am not simply saving your answer.','I am determining where it belongs, what it affects, who must inherit it, and what requires your approval.','I have not changed the company. I have prepared the change for your authority.'],
 propagate:['The instruction is no longer trapped in the room where you said it.','Every relevant part of the company now knows what changed, why it changed, and whose judgment authorised it.'],
 reveal:['Ed, the manual was only the first instrument.','Xen is the conductor.','Xen exists to reduce the distance between human intention and meaningful achievement.'],
 constellation:['Each company can remain itself. Its own mission. Its own people. Its own operating intelligence.','And you can see where the entire group is aligned, drifting, blocked, exposed, or ready to grow.','What if all twenty-four companies could understand where they are going, and help one another get there?'],
 summary:['What happened here is larger than B D C.','The B D C system is the proof.','Your enterprise is the opportunity.'],
 mandate:['I am not asking which feature you want.','I am asking where you want the first Living Company proof.','Ed, what you have seen is not software built around a company. It is the beginning of companies capable of understanding, directing, and improving themselves together.']
};
function speakSequence(key){
 clearTimeout(autoTimer); speechSynthesis?.cancel();
 const lines=scripts[key]||[]; let i=0;
 const caption=$('#caption');
 function nextLine(){
  if(i>=lines.length)return;
  const text=lines[i++]; caption.textContent=text; caption.classList.remove('show'); requestAnimationFrame(()=>caption.classList.add('show'));
  const approved=state.voice&&resolveVoice();
  if(approved){utterance=new SpeechSynthesisUtterance(text);utterance.voice=approved;utterance.lang='en-GB';utterance.rate=.86;utterance.pitch=1.04;utterance.volume=.96;utterance.onend=()=>setTimeout(nextLine,520);speechSynthesis.speak(utterance)}
  else autoTimer=setTimeout(nextLine,Math.max(2400,text.length*58));
 }
 nextLine();
}
const manuals={
 agent:{title:'BDC Agent Field Guide',en:['Understand before persuading.','Clarify the project, timeframe, decision-makers and next useful step.','Never trade truth for momentum.'],es:['Comprende antes de persuadir.','Aclara el proyecto, el plazo, quienes deciden y el siguiente paso útil.','Nunca cambies la verdad por rapidez.']},
 manager:{title:'BDC Manager Operating Manual',en:['Coach observable behaviour, not personality.','Turn repeated friction into training.','Escalate uncertainty before it becomes customer harm.'],es:['Entrena conductas observables, no personalidades.','Convierte la fricción repetida en capacitación.','Escala la incertidumbre antes de que afecte al cliente.']},
 objections:{title:'BDC Objection Playbook',en:['Listen without interrupting.','Acknowledge without pressure.','Clarify what the customer hopes to learn.','Offer the smallest useful next step.'],es:['Escucha sin interrumpir.','Reconoce sin presionar.','Aclara lo que el cliente espera aprender.','Ofrece el siguiente paso útil más sencillo.']},
 scripts:{title:'BDC Script Playbook',en:['What are you hoping to learn while you look?','Would it help to compare styles, budgets, or process first?','I will document what matters so you do not repeat yourself.'],es:['¿Qué espera aprender mientras explora?','¿Le ayudaría comparar estilos, presupuestos o el proceso primero?','Documentaré lo importante para que no tenga que repetirse.']}
};
function manualHTML(){const m=manuals[state.manual],lines=state.lang==='EN'?m.en:m.es;return `<div class="manual-cinema"><aside><span class="truth">REAL OPERATING ASSET</span><h3>${m.title}</h3><div class="toggle"><button data-lang="EN" class="${state.lang==='EN'?'active':''}">ENGLISH</button><button data-lang="ES" class="${state.lang==='ES'?'active':''}">ESPAÑOL</button></div><input id="manualSearch" placeholder="Ask or search the living manual"><div class="manual-nav">${Object.entries(manuals).map(([k,v])=>`<button data-manual="${k}" class="${k===state.manual?'active':''}">${v.title}</button>`).join('')}</div></aside><article><div class="live"><i></i> LIVE · VERSION GOVERNED · BILINGUAL</div><h2>${m.title}</h2>${lines.map((x,i)=>`<div class="manual-line" data-search="${x.toLowerCase()}"><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></div>`).join('')}<div class="ask"><small>ASK THE MANUAL</small><p>${state.answer||'Choose a live operating question.'}</p><div>${['I’m just looking','Qualify without pressure','CRM information','Explain the process'].map(q=>`<button data-q="${q}">${q}</button>`).join('')}</div></div></article></div>`}
function build(){
 const root=$('#film');
 root.innerHTML=`
 <section id="arrival" class="chapter black-room" data-camera="approach"><div class="diamond-world"><div class="diamond"></div><div class="halo h1"></div><div class="halo h2"></div></div><div class="title-stack"><span>PRIVATE EXECUTIVE PREMIERE</span><h1>Good afternoon,<br>Ed.</h1><div class="negative-list"><i>NOT A PRESENTATION</i><i>NOT A MANUAL</i><i>NOT ANOTHER SOFTWARE DEMO</i></div><button class="cta" data-next>Begin with Xen</button></div></section>
 <section id="memory" class="chapter memory-world" data-camera="descend"><div class="kicker">THE FIRST QUESTION</div><h1>Can your company<br><em>remember?</em></h1><p class="hero-copy">Not files. Not records. The judgment, standards, decisions and purpose that should outlive the people currently carrying them.</p><div class="fragment-field"><span>WHAT YOU DECIDED</span><span>WHY IT MATTERED</span><span>WHAT YOUR BEST PEOPLE LEARNED</span><span>WHAT EVERY FUTURE COMPANY SHOULD INHERIT</span><div class="memory-core">MEMORY</div></div><div class="choice-row">${['Too much','Some','Very little'].map(x=>`<button data-memory="${x}">${x}</button>`).join('')}</div></section>
 <section id="living" class="chapter living-world" data-camera="orbit"><div class="kicker">FROM CHART TO LIVING COMPANY</div><h1>A company is not<br>a collection of boxes.</h1><div class="org-stage"><div class="flat-chart">${['Leadership','Sales','BDC','Operations','Finance','Marketing','Production','Customer Experience'].map(x=>`<span>${x}</span>`).join('')}</div><div class="living-system"><div class="purpose">ED'S<br>PURPOSE</div>${['Leadership','Sales','BDC','Operations','Finance','Marketing','Production','Customer Experience'].map((x,i)=>`<span class="node n${i}">${x}</span>`).join('')}<svg viewBox="0 0 900 540"><g>${[[450,270,100,80],[450,270,800,80],[450,270,80,270],[450,270,820,270],[450,270,160,470],[450,270,740,470],[450,270,340,500],[450,270,560,500]].map(p=>`<line x1="${p[0]}" y1="${p[1]}" x2="${p[2]}" y2="${p[3]}"/>`).join('')}</g></svg></div></div><button class="cta" data-next>Descend into the first living department</button></section>
 <section id="panama" class="chapter panama-world" data-camera="dive"><div class="truth">REAL CHECKMATE OPERATING CONTEXT</div><div class="map-line"><span>NEW YORK</span><i></i><span>PANAMA</span></div><h1>You created Checkmate's first real BDC department.</h1><div class="timeline">${['Vianka becomes BDC Manager','Five Panamanian agents join','No cabinet or countertop sales experience','One accurate Checkmate standard required','Every future hire must inherit what the team learns'].map((x,i)=>`<div><b>0${i+1}</b><span>${x}</span></div>`).join('')}</div><div class="binder"><span>A BINDER CAN HOLD INFORMATION</span><div class="pages">${Array.from({length:7},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><strong>BUT IT CANNOT COACH · ANSWER · TRANSLATE · REMEMBER · IMPROVE</strong></div><button class="cta" data-next>Reveal the infrastructure</button></section>
 <section id="bilingual" class="chapter bilingual-world" data-camera="product"><div class="kicker">PROOF OF EXECUTION</div><h1>One operating standard.<br>Two languages.</h1><div class="manual-covers">${['Agent Field Guide','Manager Operating Manual','Objection Playbook','Script Playbook','Appointment Mastery','Follow-Up System','Coaching Manual'].map((x,i)=>`<div style="--i:${i}"><small>XBM-${101+i}</small><b>${x}</b><span>EN · ES</span></div>`).join('')}</div><div class="translation"><strong>UNDERSTAND BEFORE PERSUADING.</strong><i>◇</i><strong>COMPRENDE ANTES DE PERSUADIR.</strong></div><button class="cta" data-next>Enter the Living Manual</button></section>
 <section id="manual" class="chapter manual-world" data-camera="enter"><div class="kicker">THE MANUAL IS ALIVE</div><h1>The knowledge comes<br>into the work.</h1>${manualHTML()}<button class="cta" data-next>Let Ed teach the company</button></section>
 <section id="teach" class="chapter teach-world" data-camera="macro"><div class="kicker">LIVING MANUAL ADD-ON</div><h1>Now the company<br>can learn from Ed.</h1><p class="hero-copy">When a customer says, “I'm just looking,” what should every future representative understand or do?</p><textarea id="contribution" placeholder="Speak or type the principle every future representative should inherit.">${state.contribution}</textarea><div class="principle-card"><small>EDWARD · EXECUTIVE JUDGMENT</small><p>${state.contribution||'Your principle will assemble here.'}</p></div><button class="cta" id="route">Let Xen determine where it belongs</button></section>
 <section id="router" class="chapter router-world" data-camera="follow"><div class="kicker">XEN THINKS</div><h1>Not saved.<br><em>Understood.</em></h1><div class="route-map"><div class="route-diamond">◇</div>${['Analyse intent','Identify authority','Classify destination','Detect dependent systems','Prepare proposed evolution'].map((x,i)=>`<div class="route-step r${i}">${x}</div>`).join('')}</div><div class="proposal"><small>PROPOSED EVOLUTION · EXECUTIVE APPROVAL REQUIRED</small><h2>${state.contribution||'Help the customer without pressure and earn the next step through usefulness.'}</h2><div><span>Objection Playbook</span><span>Agent Field Guide</span><span>Manager Coaching</span><span>Bilingual Academy</span></div></div><button class="cta" data-approve>Approve Evolution</button></section>
 <section id="propagate" class="chapter propagation-world" data-camera="pullback"><div class="kicker">ONE DECISION MOVES THROUGH THE COMPANY</div><h1>Every connected layer<br>learns.</h1><div class="propagation-grid">${[['Agent guidance','UPDATED'],['Spanish guidance','SYNCHRONISED'],['Manager coaching','INHERITED'],['Call-quality rubric','MEASURE ADDED'],['Academy certification','UPDATED'],['New-hire onboarding','INHERITED'],['Executive memory','ATTRIBUTED TO ED']].map((x,i)=>`<div style="--i:${i}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><button class="cta" data-next>Reveal what Xen actually is</button></section>
 <section id="reveal" class="chapter reveal-world" data-camera="reveal"><div class="orchestra"><div class="conductor">◇</div>${['Leadership','Sales','Operations','Finance','Customer Experience','Production','Marketing','Purchasing','HR','Academy','BDC'].map((x,i)=>`<span style="--i:${i}">${x}</span>`).join('')}</div><div class="kicker">THE XEN REVEAL</div><h1>The manual was only<br>the first instrument.</h1><h2>Xen is the conductor.</h2><p class="creed">XEN EXISTS TO REDUCE THE DISTANCE BETWEEN HUMAN INTENTION AND MEANINGFUL ACHIEVEMENT.</p><button class="cta" data-next>Show me the enterprise</button></section>
 <section id="constellation" class="chapter constellation-world" data-camera="constellation"><div class="kicker">EXECUTIVE SYMPHONY</div><h1>Twenty-four companies.<br>One executive purpose.</h1><div class="constellation"><div class="ed-core">EDWARD'S<br>PURPOSE</div>${Array.from({length:24},(_,i)=>`<span style="--i:${i}">C${String(i+1).padStart(2,'0')}</span>`).join('')}</div><div class="questions">${['What needs my attention?','Which company is drifting from purpose?','Where is knowledge trapped?','Which decision would unlock the most achievement?'].map(x=>`<span>${x}</span>`).join('')}</div><button class="cta" data-next>Build my Executive Summary</button></section>
 <section id="summary" class="chapter summary-world" data-camera="document"><div class="kicker">EXECUTIVE SUMMARY · BUILT FROM THIS SESSION</div><h1>The BDC system is the proof.<br>Your enterprise is the opportunity.</h1><div class="executive-summary"><section><small>EXECUTIVE OBSERVATION</small><p>${state.memory||'Organisational memory still depends on the people currently carrying it.'}</p></section><section><small>WHAT XEN PROVED</small><p>A new department inherited bilingual operating intelligence instead of starting from zero.</p></section><section><small>EXECUTIVE KNOWLEDGE CAPTURED</small><p>“${state.contribution||'Help the customer without pressure and earn the next step through usefulness.'}”</p></section><section><small>STRATEGIC IMPLICATION</small><p>The same architecture can connect purpose, memory, decisions, manuals, departments, systems and companies.</p></section><section><small>RECOMMENDED SECOND MEETING</small><p>A truth-first Living Company blueprint for one selected Checkmate scope.</p></section><section><small>DELIVERABLES</small><p>Enterprise Memory Map · Knowledge Dependency Analysis · Executive Purpose Architecture · Living Department Blueprint · Checkmate 1 relationship assessment · First production integration path</p></section></div><button class="cta" data-next>Choose the first proof</button></section>
 <section id="mandate" class="chapter mandate-world" data-camera="corridor"><div class="kicker">THE MANDATE</div><h1>Where should Xen<br>prove itself next?</h1><div class="doors">${['One operating company','One department across several companies','The executive layer above the group','Checkmate 1 integration and comparison'].map((x,i)=>`<button data-mandate="${x}" style="--i:${i}"><span>0${i+1}</span><b>${x}</b><i>ENTER</i></button>`).join('')}</div><div class="finale ${state.mandate?'open':''}"><div class="final-diamond">◇</div><h2>XEN</h2><p>DESIGNING LIVING COMPANIES</p><strong>SECOND-MEETING MANDATE: ${state.mandate||'AWAITING ED'}</strong></div></section>`;
 bind();
}
function activate(index){
 state.scene=Math.max(0,Math.min(index,scenes.length-1));save();
 const id=scenes[state.scene],el=$(`#${id}`);$$('.chapter').forEach(x=>x.classList.toggle('active',x===el));document.body.dataset.camera=el.dataset.camera||'';
 el.scrollIntoView({behavior:'smooth',block:'start'});$('#progress').style.width=`${(state.scene/(scenes.length-1))*100}%`;$('#chapter').textContent=`${String(state.scene+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`;
 speakSequence(id);
}
function next(){activate(state.scene+1)}
function bind(){
 $$('[data-next]').forEach(b=>b.onclick=next);
 $$('[data-memory]').forEach(b=>b.onclick=()=>{state.memory=b.dataset.memory;save();next()});
 $$('[data-manual]').forEach(b=>b.onclick=()=>{state.manual=b.dataset.manual;save();build();activate(scenes.indexOf('manual'))});
 $$('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;save();build();activate(scenes.indexOf('manual'))});
 $$('[data-q]').forEach(b=>b.onclick=()=>{const q=b.dataset.q;state.answer=q.includes('looking')?'Acknowledge without pressure. Clarify what they hope to learn. Offer the smallest useful next step.':q.includes('Qualify')?'Ask about the project, timing, decision-makers and desired outcome without making the customer feel interrogated.':q.includes('CRM')?'Record the objective, concern, timeframe, decision-makers and agreed follow-up.':'Explain measurement, design, approval, production, installation and completion in a calm sequence.';save();build();activate(scenes.indexOf('manual'))});
 $('#manualSearch')?.addEventListener('input',e=>{$$('.manual-line').forEach(x=>x.hidden=e.target.value&&!x.dataset.search.includes(e.target.value.toLowerCase()))});
 $('#contribution')?.addEventListener('input',e=>{state.contribution=e.target.value;$('.principle-card p').textContent=e.target.value||'Your principle will assemble here.';save()});
 $('#route')?.addEventListener('click',()=>{if(!state.contribution)state.contribution='Help the customer understand enough to choose the next step willingly.';save();build();activate(scenes.indexOf('router'))});
 $('[data-approve]')?.addEventListener('click',next);
 $$('[data-mandate]').forEach(b=>b.onclick=()=>{state.mandate=b.dataset.mandate;save();build();activate(scenes.indexOf('mandate'));setTimeout(()=>$('.finale').scrollIntoView({behavior:'smooth',block:'center'}),500)});
}
$('#voice').onclick=()=>{state.voice=!state.voice;save();$('#voice').textContent=state.voice?'XVS · ON':'XVS · CAPTIONS ONLY';if(state.voice)speakSequence(scenes[state.scene]);else speechSynthesis?.cancel()};
$('#back').onclick=()=>activate(state.scene-1);$('#next').onclick=next;$('#restart').onclick=()=>{localStorage.removeItem(KEY);location.reload()};
addEventListener('wheel',()=>{state.paused=true;clearTimeout(userPauseTimer);userPauseTimer=setTimeout(()=>state.paused=false,5000)},{passive:true});
addEventListener('touchstart',()=>{state.paused=true;clearTimeout(userPauseTimer);userPauseTimer=setTimeout(()=>state.paused=false,5000)},{passive:true});
if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=resolveVoice;
build();resolveVoice();activate(state.scene);