const VERSION='6.0.0-master-director';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const film=$('#film'), caption=$('#caption'), chapter=$('#chapter'), progress=$('#progress'), voiceButton=$('#voice');
const sceneIds=['arrival','memory','living','panama','bilingual','manual','teach','router','propagate','reveal','constellation','summary','mandate'];
const state={scene:0,started:false,token:0,voice:null,memory:'',answer:'',contribution:'',mandate:'',manual:'agent',lang:'EN'};
let utterance=null, fallbackTimer=null;
const femaleNames=['Sonia','Libby','Serena','Maisie','Kate','Stephanie','Martha','Hazel','Fiona','Moira','Tessa','Amy','Emma','Google UK English Female'];
const rejected=/\b(male|daniel|george|oliver|ryan|arthur|brian|christopher|guy|james|john|mark|matthew|thomas)\b/i;
const greeting=()=>{const h=new Date().getHours();return h>=5&&h<12?'Good morning':h>=12&&h<18?'Good afternoon':'Good evening'};
function resolveVoice(){const voices=('speechSynthesis'in window)?speechSynthesis.getVoices():[];state.voice=voices.find(v=>/^en[-_]GB/i.test(v.lang)&&femaleNames.some(n=>v.name.toLowerCase().includes(n.toLowerCase())))||voices.find(v=>/^en[-_]GB/i.test(v.lang)&&!rejected.test(v.name))||null;voiceButton.textContent=state.voice?`XVS · ${state.voice.name.replace(/Microsoft|Google|Online|Natural|\(.*?\)/gi,'').trim()}`:'XVS · CAPTIONS';return state.voice}
function cancelTimeline(){state.token++;clearTimeout(fallbackTimer);if('speechSynthesis'in window)speechSynthesis.cancel();utterance=null;caption.textContent='';caption.classList.remove('show');$$('[data-beat]').forEach(x=>x.classList.remove('beat-active'))}
function wait(ms,token){return new Promise(resolve=>{fallbackTimer=setTimeout(()=>resolve(token===state.token),ms)})}
function speak(text,token){return new Promise(resolve=>{if(token!==state.token){resolve(false);return}caption.textContent=text;caption.classList.remove('show');requestAnimationFrame(()=>caption.classList.add('show'));const voice=resolveVoice();if(!voice||!state.started||!('speechSynthesis'in window)){fallbackTimer=setTimeout(()=>resolve(token===state.token),Math.max(1800,text.length*48));return}utterance=new SpeechSynthesisUtterance(text);utterance.voice=voice;utterance.lang=voice.lang||'en-GB';utterance.rate=.87;utterance.pitch=1.03;utterance.volume=1;utterance.onend=()=>setTimeout(()=>resolve(token===state.token),280);utterance.onerror=()=>{voiceButton.textContent='XVS · CAPTIONS';fallbackTimer=setTimeout(()=>resolve(token===state.token),Math.max(1800,text.length*48))};speechSynthesis.speak(utterance)})}
function activateBeat(selector){$$('[data-beat]').forEach(x=>x.classList.remove('beat-active'));const el=$(selector);if(el){el.classList.add('beat-active');el.scrollIntoView({behavior:'smooth',block:'center'})}}
const manuals={agent:{title:'BDC Agent Field Guide',en:['Understand before persuading.','Clarify the project, timeframe, decision-makers and next useful step.','Never trade truth for momentum.'],es:['Comprende antes de persuadir.','Aclara el proyecto, el plazo, quienes deciden y el siguiente paso útil.','Nunca cambies la verdad por rapidez.']},manager:{title:'BDC Manager Operating Manual',en:['Coach observable behaviour, not personality.','Turn repeated friction into training.','Escalate uncertainty before it becomes customer harm.'],es:['Entrena conductas observables, no personalidades.','Convierte la fricción repetida en capacitación.','Escala la incertidumbre antes de que afecte al cliente.']},objections:{title:'BDC Objection Playbook',en:['Listen without interrupting.','Acknowledge without pressure.','Clarify what the customer hopes to learn.','Offer the smallest useful next step.'],es:['Escucha sin interrumpir.','Reconoce sin presionar.','Aclara lo que el cliente espera aprender.','Ofrece el siguiente paso útil más sencillo.']},scripts:{title:'BDC Script Playbook',en:['What are you hoping to learn while you look?','Would it help to compare styles, budgets, or process first?','I will document what matters so you do not repeat yourself.'],es:['¿Qué espera aprender mientras explora?','¿Le ayudaría comparar estilos, presupuestos o el proceso primero?','Documentaré lo importante para que no tenga que repetirse.']}};
function manualHTML(){const m=manuals[state.manual],lines=state.lang==='EN'?m.en:m.es;return `<div class="manual-cinema"><aside><span class="truth">REAL OPERATING ASSET</span><h3>${m.title}</h3><div class="toggle"><button data-lang="EN" class="${state.lang==='EN'?'active':''}">ENGLISH</button><button data-lang="ES" class="${state.lang==='ES'?'active':''}">ESPAÑOL</button></div><input id="manualSearch" placeholder="Ask or search the living manual"><div class="manual-nav">${Object.entries(manuals).map(([k,v])=>`<button data-manual="${k}" class="${k===state.manual?'active':''}">${v.title}</button>`).join('')}</div></aside><article><div class="live" data-beat="manual-status"><i></i> LIVE · VERSION GOVERNED · BILINGUAL</div><h2>${m.title}</h2>${lines.map((x,i)=>`<div class="manual-line" data-beat="manual-${i}" data-search="${x.toLowerCase()}"><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></div>`).join('')}<div class="ask" data-beat="manual-ask"><small>ASK THE MANUAL</small><p>${state.answer||'Choose a live operating question.'}</p><div>${['I’m just looking','Qualify without pressure','CRM information','Explain the process'].map(q=>`<button data-q="${q}">${q}</button>`).join('')}</div></div></article></div>`}
function build(){film.innerHTML=`
<section id="arrival" class="chapter black-room active" data-camera="approach"><div class="diamond-world" data-beat="arrival-diamond"><div class="diamond"></div><div class="halo h1"></div><div class="halo h2"></div></div><div class="title-stack"><span>PRIVATE EXECUTIVE PREMIERE</span><h1>${greeting()},<br>Ed.</h1><div class="negative-list" data-beat="arrival-list"><i>NOT A PRESENTATION</i><i>NOT A MANUAL</i><i>NOT ANOTHER SOFTWARE DEMO</i></div><button class="cta" id="begin">Begin with Xen</button></div></section>
<section id="memory" class="chapter memory-world" data-camera="descend"><div class="kicker">THE FIRST QUESTION</div><h1>Can your company<br><em>remember?</em></h1><p class="hero-copy">Not files. Not records. The judgment, standards, decisions and purpose that should outlive the people currently carrying them.</p><div class="fragment-field">${['WHAT YOU DECIDED','WHY IT MATTERED','WHAT YOUR BEST PEOPLE LEARNED','WHAT EVERY FUTURE COMPANY SHOULD INHERIT'].map((x,i)=>`<span data-beat="memory-${i}">${x}</span>`).join('')}<div class="memory-core" data-beat="memory-core">MEMORY</div></div><div class="choice-row">${['Too much','Some','Very little'].map(x=>`<button data-memory="${x}">${x}</button>`).join('')}</div></section>
<section id="living" class="chapter living-world" data-camera="orbit"><div class="kicker">FROM CHART TO LIVING COMPANY</div><h1>A company is not<br>a collection of boxes.</h1><div class="org-stage"><div class="flat-chart" data-beat="flat-chart">${['Leadership','Sales','BDC','Operations','Finance','Marketing','Production','Customer Experience'].map(x=>`<span>${x}</span>`).join('')}</div><div class="living-system" data-beat="living-system"><div class="purpose">ED'S<br>PURPOSE</div>${['Leadership','Sales','BDC','Operations','Finance','Marketing','Production','Customer Experience'].map((x,i)=>`<span class="node n${i}">${x}</span>`).join('')}<svg viewBox="0 0 900 540"><g>${[[450,270,100,80],[450,270,800,80],[450,270,80,270],[450,270,820,270],[450,270,160,470],[450,270,740,470],[450,270,340,500],[450,270,560,500]].map(p=>`<line x1="${p[0]}" y1="${p[1]}" x2="${p[2]}" y2="${p[3]}"/>`).join('')}</g></svg></div></div></section>
<section id="panama" class="chapter panama-world" data-camera="dive"><div class="truth">REAL CHECKMATE OPERATING CONTEXT</div><div class="map-line" data-beat="map"><span>NEW YORK</span><i></i><span>PANAMA</span></div><h1>You created Checkmate's first real BDC department.</h1><div class="timeline">${['Vianka becomes BDC Manager','Five Panamanian agents join','No cabinet or countertop sales experience','One accurate Checkmate standard required','Every future hire must inherit what the team learns'].map((x,i)=>`<div data-beat="panama-${i}"><b>0${i+1}</b><span>${x}</span></div>`).join('')}</div><div class="binder" data-beat="binder"><span>A BINDER CAN HOLD INFORMATION</span><div class="pages">${Array.from({length:7},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><strong>BUT IT CANNOT COACH · ANSWER · TRANSLATE · REMEMBER · IMPROVE</strong></div></section>
<section id="bilingual" class="chapter bilingual-world" data-camera="product"><div class="kicker">PROOF OF EXECUTION</div><h1>One operating standard.<br>Two languages.</h1><div class="manual-covers">${['Agent Field Guide','Manager Operating Manual','Objection Playbook','Script Playbook','Appointment Mastery','Follow-Up System','Coaching Manual'].map((x,i)=>`<div data-beat="cover-${i}" style="--i:${i}"><small>XBM-${101+i}</small><b>${x}</b><span>EN · ES</span></div>`).join('')}</div><div class="translation" data-beat="translation"><strong>UNDERSTAND BEFORE PERSUADING.</strong><i>◇</i><strong>COMPRENDE ANTES DE PERSUADIR.</strong></div></section>
<section id="manual" class="chapter manual-world" data-camera="enter"><div class="kicker">THE MANUAL IS ALIVE</div><h1>The knowledge comes<br>into the work.</h1>${manualHTML()}<button class="cta" data-next>Let Ed teach the company</button></section>
<section id="teach" class="chapter teach-world" data-camera="macro"><div class="kicker">LIVING MANUAL ADD-ON</div><h1>Now the company<br>can learn from Ed.</h1><p class="hero-copy">When a customer says, “I'm just looking,” what should every future representative understand or do?</p><textarea id="contribution" placeholder="Speak or type the principle every future representative should inherit.">${state.contribution}</textarea><div class="principle-card" data-beat="principle"><small>EDWARD · EXECUTIVE JUDGMENT</small><p>${state.contribution||'Your principle will assemble here.'}</p></div><button class="cta" id="route">Let Xen determine where it belongs</button></section>
<section id="router" class="chapter router-world" data-camera="follow"><div class="kicker">XEN THINKS</div><h1>Not saved.<br><em>Understood.</em></h1><div class="route-map"><div class="route-diamond">◇</div>${['Analyse intent','Identify authority','Classify destination','Detect dependent systems','Prepare proposed evolution'].map((x,i)=>`<div class="route-step r${i}" data-beat="route-${i}">${x}</div>`).join('')}</div><div class="proposal" data-beat="proposal"><small>PROPOSED EVOLUTION · EXECUTIVE APPROVAL REQUIRED</small><h2>${state.contribution||'Help the customer without pressure and earn the next step through usefulness.'}</h2><div><span>Objection Playbook</span><span>Agent Field Guide</span><span>Manager Coaching</span><span>Bilingual Academy</span></div></div><button class="cta" data-approve>Approve Evolution</button></section>
<section id="propagate" class="chapter propagation-world" data-camera="pullback"><div class="kicker">ONE DECISION MOVES THROUGH THE COMPANY</div><h1>Every connected layer<br>learns.</h1><div class="propagation-grid">${[['Agent guidance','UPDATED'],['Spanish guidance','SYNCHRONISED'],['Manager coaching','INHERITED'],['Call-quality rubric','MEASURE ADDED'],['Academy certification','UPDATED'],['New-hire onboarding','INHERITED'],['Executive memory','ATTRIBUTED TO ED']].map((x,i)=>`<div data-beat="prop-${i}" style="--i:${i}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></section>
<section id="reveal" class="chapter reveal-world" data-camera="reveal"><div class="orchestra" data-beat="orchestra"><div class="conductor">◇</div>${['Leadership','Sales','Operations','Finance','Customer Experience','Production','Marketing','Purchasing','HR','Academy','BDC'].map((x,i)=>`<span style="--i:${i}">${x}</span>`).join('')}</div><div class="kicker">THE XEN REVEAL</div><h1>The manual was only<br>the first instrument.</h1><h2>Xen is the conductor.</h2><p class="creed" data-beat="creed">XEN EXISTS TO REDUCE THE DISTANCE BETWEEN HUMAN INTENTION AND MEANINGFUL ACHIEVEMENT.</p></section>
<section id="constellation" class="chapter constellation-world" data-camera="constellation"><div class="kicker">EXECUTIVE SYMPHONY</div><h1>Twenty-four companies.<br>One executive purpose.</h1><div class="constellation" data-beat="constellation"><div class="ed-core">EDWARD'S<br>PURPOSE</div>${Array.from({length:24},(_,i)=>`<span style="--i:${i}">C${String(i+1).padStart(2,'0')}</span>`).join('')}</div><div class="questions">${['What needs my attention?','Which company is drifting from purpose?','Where is knowledge trapped?','Where is money leaking?','What should I decide today?'].map((x,i)=>`<div data-beat="question-${i}">${x}</div>`).join('')}</div></section>
<section id="summary" class="chapter summary-world" data-camera="assemble"><div class="kicker">EXECUTIVE SUMMARY</div><h1>The BDC system<br>is the proof.</h1><div class="summary-stack"><div data-beat="sum-0"><small>THE QUESTION</small><b>Can Checkmate preserve executive judgment?</b><span>${state.memory||'Awaiting Ed'}</span></div><div data-beat="sum-1"><small>THE PROOF</small><b>Bilingual living operating infrastructure</b><span>BDC manuals · coaching · QA · Academy · memory</span></div><div data-beat="sum-2"><small>THE TRANSFORMATION</small><b>One executive decision becomes governed company knowledge</b><span>${state.contribution||'Awaiting Ed’s contribution'}</span></div><div data-beat="sum-3"><small>THE OPPORTUNITY</small><b>Twenty-four companies directed toward purpose</b><span>Each company remains itself. The enterprise learns together.</span></div></div></section>
<section id="mandate" class="chapter mandate-world" data-camera="corridor"><div class="kicker">THE MANDATE</div><h1>Where should Xen<br>prove itself next?</h1><div class="doors">${['One operating company','One department across several companies','The executive layer above the group','Checkmate 1 integration and comparison'].map((x,i)=>`<button data-mandate="${x}" style="--i:${i}"><span>0${i+1}</span><b>${x}</b><i>ENTER</i></button>`).join('')}</div><div class="finale ${state.mandate?'open':''}"><div class="final-diamond">◇</div><h2>XEN</h2><p>DESIGNING LIVING COMPANIES</p><strong>SECOND-MEETING MANDATE: ${state.mandate||'AWAITING ED'}</strong></div></section>`;bindDynamic()}
const plans={
arrival:{auto:true,beats:[['#arrival [data-beat="arrival-diamond"]',()=>`${greeting()}, Ed.`],['#arrival [data-beat="arrival-diamond"]','I am Xen.'],['#arrival [data-beat="arrival-list"]','Darren asked me to show you something he did not originally intend to build.'],['#arrival [data-beat="arrival-list"]','This is a company learning how to come alive.']]},
memory:{pause:true,beats:[['#memory [data-beat="memory-0"]','Ed, can your company remember?'],['#memory [data-beat="memory-1"]','Not files. Not records. Not data stored somewhere.'],['#memory [data-beat="memory-2"]','Can it remember what you decided, why it mattered, what your best people learned, and what every future company should inherit?'],['#memory [data-beat="memory-core"]','If the right person leaves, how much of the company leaves with them?']]},
living:{auto:true,beats:[['#living [data-beat="flat-chart"]','Most software shows a company as boxes, records, and reports.'],['#living [data-beat="flat-chart"]','But a company is not a collection of boxes.'],['#living [data-beat="living-system"]','It is purpose moving through people, decisions, departments, systems, and time.'],['#living [data-beat="living-system"]','A Living Company remembers where it is going, understands what is blocking it, teaches its people, and helps leadership move intention into achievement.'],['#living [data-beat="living-system"]','The first living part of Checkmate began with one new department.']]},
panama:{auto:true,beats:[['#panama [data-beat="map"]',"You created Checkmate's first real B D C department in Panama."],['#panama [data-beat="panama-0"]','Vianka became B D C Manager.'],['#panama [data-beat="panama-1"]','Five Panamanian agents joined the department.'],['#panama [data-beat="panama-2"]','They had no cabinet or countertop sales experience.'],['#panama [data-beat="panama-3"]','They needed one accurate Checkmate standard.'],['#panama [data-beat="panama-4"]','Every future hire needed to inherit what the team learned.'],['#panama [data-beat="binder"]',"Darren's first problem was not how to make a manual."],['#panama [data-beat="binder"]','It was how to give six people operating judgment they did not yet possess.'],['#panama [data-beat="binder"]','A binder could hold information. But it could not coach, answer, translate, remember, or improve.']]},
bilingual:{auto:true,beats:[['#bilingual [data-beat="cover-0"]','We did not translate one document.'],['#bilingual [data-beat="cover-3"]','We built one operating standard that could live in two languages without losing its meaning.'],['#bilingual [data-beat="translation"]','The same customer promise. The same coaching logic. The same operating intent.']]},
manual:{pause:true,beats:[['#manual [data-beat="manual-status"]','Let me walk you through what the agent sees.'],['#manual [data-beat="manual-0"]','The agent does not leave the work to search for knowledge.'],['#manual [data-beat="manual-1"]','The knowledge comes into the work.'],['#manual [data-beat="manual-ask"]','Ed, choose what the agent needs help with.']]},
teach:{pause:true,beats:[['#teach [data-beat="principle"]','But this is where the system becomes a Living Company.'],['#teach [data-beat="principle"]','When a customer says, I am just looking, what should every future representative understand or do?'],['#teach [data-beat="principle"]','Tell me in your own words.']]},
router:{pause:true,beats:[['#router [data-beat="route-0"]','I am not simply saving your answer.'],['#router [data-beat="route-1"]','I am determining where it belongs.'],['#router [data-beat="route-2"]','What it affects.'],['#router [data-beat="route-3"]','Who must inherit it.'],['#router [data-beat="proposal"]','I have not changed the company. I have prepared the change for your authority.']]},
propagate:{auto:true,beats:[...Array.from({length:7},(_,i)=>[`#propagate [data-beat="prop-${i}"]`,i===0?'The instruction is no longer trapped in the room where you said it.':i===6?'Every relevant part of the company now knows what changed, why it changed, and whose judgment authorised it.':'The approved principle is propagating through the company.'])]},
reveal:{auto:true,beats:[['#reveal [data-beat="orchestra"]','Ed, the manual was only the first instrument.'],['#reveal [data-beat="orchestra"]','Xen is the conductor.'],['#reveal [data-beat="creed"]','Xen connects purpose, memory, people, departments, systems, and decisions so the company can act as one living organisation.'],['#reveal [data-beat="creed"]','Xen exists to reduce the distance between human intention and meaningful achievement.']]},
constellation:{auto:true,beats:[['#constellation [data-beat="constellation"]','Each company can remain itself. Its own mission. Its own people. Its own operating intelligence.'],['#constellation [data-beat="question-1"]','And you can see where the entire group is aligned, drifting, blocked, exposed, or ready to grow.'],['#constellation [data-beat="question-4"]','What if all twenty-four companies could understand where they are going, and help one another get there?']]},
summary:{auto:true,beats:[['#summary [data-beat="sum-0"]','What happened here is larger than B D C.'],['#summary [data-beat="sum-1"]','The B D C system is the proof.'],['#summary [data-beat="sum-2"]','Your judgment became living company knowledge.'],['#summary [data-beat="sum-3"]','Your enterprise is the opportunity.']]},
mandate:{pause:true,beats:[['#mandate .doors','I am not asking which feature you want.'],['#mandate .doors','I am asking where you want the first Living Company proof.'],['#mandate .finale','Ed, what you have seen is not software built around a company. It is the beginning of companies capable of understanding, directing, and improving themselves together.']]}
};
async function runScene(id){cancelTimeline();const token=state.token;const plan=plans[id];if(!state.started||!plan)return;for(const [selector,line] of plan.beats){if(token!==state.token)return;activateBeat(selector);const text=typeof line==='function'?line():line;const ok=await speak(text,token);if(!ok)return}if(plan.auto&&token===state.token){await wait(650,token);if(token===state.token)gotoScene(state.scene+1,{narrate:true})}}
function gotoScene(index,{narrate=true}={}){cancelTimeline();state.scene=Math.max(0,Math.min(index,sceneIds.length-1));const id=sceneIds[state.scene],target=$(`#${id}`);$$('.chapter').forEach(x=>x.classList.toggle('active',x===target));document.body.dataset.camera=target?.dataset.camera||'';target?.scrollIntoView({behavior:'smooth',block:'start'});progress.style.width=`${state.scene/(sceneIds.length-1)*100}%`;chapter.textContent=`${String(state.scene+1).padStart(2,'0')} / ${String(sceneIds.length).padStart(2,'0')}`;if(narrate&&state.started)runScene(id)}
function begin(){if(state.started){runScene(sceneIds[state.scene]);return}state.started=true;resolveVoice();gotoScene(0,{narrate:true})}
function restart(){cancelTimeline();state.scene=0;state.started=false;state.memory='';state.answer='';state.contribution='';state.mandate='';state.manual='agent';state.lang='EN';build();gotoScene(0,{narrate:false});voiceButton.textContent='XVS · READY'}
function bindDynamic(){
$('#begin')?.addEventListener('click',begin);
$$('[data-memory]').forEach(b=>b.addEventListener('click',()=>{state.memory=b.dataset.memory;gotoScene(2,{narrate:true})}));
$$('[data-manual]').forEach(b=>b.addEventListener('click',()=>{state.manual=b.dataset.manual;build();gotoScene(5,{narrate:false})}));
$$('[data-lang]').forEach(b=>b.addEventListener('click',()=>{state.lang=b.dataset.lang;build();gotoScene(5,{narrate:false})}));
$$('[data-q]').forEach(b=>b.addEventListener('click',()=>{const q=b.dataset.q;state.answer=q.includes('looking')?'Acknowledge without pressure. Clarify what they hope to learn. Offer the smallest useful next step.':q.includes('Qualify')?'Ask about project, timing, decision-makers and desired outcome without making the customer feel interrogated.':q.includes('CRM')?'Record objective, concern, timeframe, decision-makers and agreed follow-up.':'Explain measurement, design, approval, production, installation and completion in a calm sequence.';build();gotoScene(5,{narrate:false});setTimeout(()=>{activateBeat('#manual [data-beat="manual-ask"]');speak(state.answer,state.token)},250)}));
$('#manualSearch')?.addEventListener('input',e=>$$('.manual-line').forEach(x=>x.hidden=e.target.value&&!x.dataset.search.includes(e.target.value.toLowerCase())));
$('#contribution')?.addEventListener('input',e=>{state.contribution=e.target.value;$('.principle-card p').textContent=e.target.value||'Your principle will assemble here.'});
$('#route')?.addEventListener('click',()=>{if(!state.contribution)state.contribution='Help the customer understand enough to choose the next step willingly.';build();gotoScene(7,{narrate:true})});
$('[data-approve]')?.addEventListener('click',()=>gotoScene(8,{narrate:true}));
$('[data-next]')?.addEventListener('click',()=>gotoScene(state.scene+1,{narrate:true}));
$$('[data-mandate]').forEach(b=>b.addEventListener('click',()=>{state.mandate=b.dataset.mandate;build();gotoScene(12,{narrate:false});$('.finale')?.classList.add('open');$('.finale')?.scrollIntoView({behavior:'smooth',block:'center'})}));
}
$('#back').addEventListener('click',()=>{if(state.started)gotoScene(state.scene-1,{narrate:true})});
$('#next').addEventListener('click',()=>{if(state.started)gotoScene(state.scene+1,{narrate:true})});
$('#restart').addEventListener('click',restart);
voiceButton.addEventListener('click',()=>state.started?runScene(sceneIds[state.scene]):begin());
document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&state.started){e.preventDefault();gotoScene(state.scene-1,{narrate:true})}if(e.key==='ArrowRight'&&state.started){e.preventDefault();gotoScene(state.scene+1,{narrate:true})}if((e.key==='Enter'||e.key===' ')&&!state.started){e.preventDefault();begin()}});
if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=resolveVoice;
build();gotoScene(0,{narrate:false});resolveVoice();