const VERSION='4.0.0-symphony';
const KEY='xei.ed.symphony.v4';
const scenes=['intro','memory','living','origin','bilingual','manual','evolve','propagate','orchestra','purpose','close'];
const defaults={scene:0,voice:true,manual:'agent',language:'EN',answer:'',contribution:'',started:false};
let state=load();
let selectedVoice=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));updateChrome()}
function pickXVSVoice(){
 const voices=speechSynthesis?.getVoices?.()||[];
 const femaleNames=['Serena','Sonia','Libby','Maisie','Kate','Stephanie','Martha','Hazel','Fiona','Moira','Tessa','Amy','Emma'];
 selectedVoice=voices.find(v=>v.lang?.toLowerCase().startsWith('en-gb')&&femaleNames.some(n=>v.name.toLowerCase().includes(n.toLowerCase())))
 || voices.find(v=>v.lang?.toLowerCase().startsWith('en-gb')&&!/(male|daniel|george|oliver|ryan)/i.test(v.name))
 || voices.find(v=>/female/i.test(v.name)&&/^en/i.test(v.lang))
 || null;
 document.documentElement.dataset.xvs=selectedVoice?'ready':'fallback';
}
function speak(text,force=false){
 if((!state.voice&&!force)||!text||!('speechSynthesis'in window))return;
 pickXVSVoice(); speechSynthesis.cancel();
 const u=new SpeechSynthesisUtterance(text); if(selectedVoice)u.voice=selectedVoice;
 u.lang='en-GB';u.rate=.88;u.pitch=1.08;u.volume=.96;
 speechSynthesis.speak(u);
}
function updateChrome(){
 $('#progress').style.width=`${(state.scene/(scenes.length-1))*100}%`;
 $('#sceneCount').textContent=`${String(state.scene+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`;
 $('#voice').textContent=`XVS · British Woman ${state.voice?'On':'Off'}`;
 $('#back').disabled=state.scene===0;
}
const btn=(label,id='next',cls='primary')=>`<button class="btn ${cls}" id="${id}">${label}<span>↗</span></button>`;
const shell=(eyebrow,title,body,actions='',cls='')=>`<section class="scene ${cls}"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1>${body}<div class="actions">${actions}</div></section>`;
const manualData={
 agent:{title:'BDC Agent Field Guide',en:['Understand before persuading.','Clarify the project, timeframe, decision-makers and next useful step.','Never trade truth for momentum.'],es:['Comprende antes de persuadir.','Aclara el proyecto, el plazo, quienes deciden y el siguiente paso útil.','Nunca cambies la verdad por rapidez.']},
 manager:{title:'BDC Manager Operating Manual',en:['Coach observable behaviour, not personality.','Turn repeated friction into training.','Escalate uncertainty before it becomes customer harm.'],es:['Entrena conductas observables, no personalidades.','Convierte la fricción repetida en capacitación.','Escala la incertidumbre antes de que afecte al cliente.']},
 objections:{title:'BDC Objection Playbook',en:['Listen without interrupting.','Acknowledge without pressure.','Offer the smallest useful next step.'],es:['Escucha sin interrumpir.','Reconoce sin presionar.','Ofrece el siguiente paso útil más sencillo.']}
};
function manualViewer(){const m=manualData[state.manual],lines=state.language==='EN'?m.en:m.es;return `<div class="manual-shell"><aside><div class="label">LIVING MANUAL RUNTIME</div><h3>${m.title}</h3><div class="segmented"><button data-lang="EN" class="${state.language==='EN'?'active':''}">ENGLISH</button><button data-lang="ES" class="${state.language==='ES'?'active':''}">ESPAÑOL</button></div><input id="manualSearch" placeholder="Ask or search this manual"><div class="manual-tabs">${Object.entries(manualData).map(([k,v])=>`<button data-manual="${k}" class="${k===state.manual?'active':''}">${v.title}</button>`).join('')}</div><div class="runtime-note">Searchable · Bilingual · Coachable · Version governed · Inheritable</div></aside><article><div class="live-status"><i></i> LIVE · CANONICAL</div><h2>${m.title}</h2>${lines.map((x,i)=>`<div class="manual-line" data-search="${esc(x.toLowerCase())}"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}<div class="ask-panel"><span>Ask the manual</span><p id="answerText">${state.answer||'Select a question to see the living guidance respond.'}</p><div class="question-row"><button data-question="What do I say when they are just looking?">Just looking</button><button data-question="How do I qualify without pressure?">Qualify</button><button data-question="What must I record?">CRM record</button></div></div></article></div>`}
function render(){speechSynthesis?.cancel();const scene=scenes[state.scene];let html='',n='';
 if(scene==='intro'){html=`<section class="scene cinema"><div class="diamond-stage"><div class="diamond-cursor"><i></i></div><div class="rings"></div></div><div class="intro-copy"><div class="eyebrow">XENESIS · PRIVATE EXECUTIVE PREMIERE</div><h1>Good afternoon, Ed.</h1><p class="lead">I am Xen. I was built to reduce the distance between your intention and what your companies can achieve.</p><div class="actions">${btn('Enter the Symphony','begin','xen')}</div></div></section>`;n='Good afternoon, Ed. I am Xen. I was built to reduce the distance between your intention and what your companies can achieve.'}
 if(scene==='memory'){html=shell('THE FIRST QUESTION','Can your company remember?',`<p class="lead">Not files. Not data. Can it remember what you decided, why it mattered, what your best people learned, and what every future company should inherit?</p><div class="memory-field"><span>DECISIONS</span><span>JUDGMENT</span><span>STANDARDS</span><span>PURPOSE</span><div class="memory-core">REMEMBER</div></div>`,btn('Show me a Living Company'));n='Can your company remember? Not files. Not data. Can it remember what you decided, why it mattered, and what every future company should inherit?'}
 if(scene==='living'){html=shell('LIVING COMPANY','A company should not wait to be operated.',`<p class="lead">It should understand its purpose, preserve leadership judgment, coordinate departments, surface friction, teach its people and guide action.</p><div class="living-company"><div class="purpose-core">ED'S<br>PURPOSE</div>${['LEADERSHIP','SALES','BDC','OPERATIONS','FINANCE','MARKETING'].map((x,i)=>`<div class="company-node n${i}">${x}</div>`).join('')}<svg viewBox="0 0 800 440" aria-hidden="true"><path d="M400 220L135 82M400 220L665 82M400 220L105 330M400 220L695 330M400 220L280 390M400 220L520 390"/></svg></div>`,btn('See the first living organ'));n='A Living Company understands its purpose, preserves leadership judgment, coordinates departments, teaches its people and guides action.'}
 if(scene==='origin'){html=shell('WHERE IT BEGAN','Ed built the first real Checkmate BDC department in Panama.',`<p class="lead">Vianka and five agents needed to serve Checkmate customers without prior cabinet or countertop sales experience. Darren designed the infrastructure so they would not have to rely on memory, guesswork or scattered documents.</p><div class="timeline"><div><b>01</b><span>Ed creates the BDC department</span></div><div><b>02</b><span>Vianka leads five new agents</span></div><div><b>03</b><span>Knowledge becomes bilingual operating infrastructure</span></div><div><b>04</b><span>Every future hire inherits the system</span></div></div>`,btn('Open the bilingual infrastructure','next','xen'));n='Ed built the first real Checkmate B D C department in Panama. Darren designed the infrastructure so the team could inherit operating intelligence instead of relying on guesswork.'}
 if(scene==='bilingual'){html=shell('BILINGUAL INFRASTRUCTURE','One standard. Two languages. No loss of meaning.',`<div class="language-bridge"><div><small>ENGLISH</small><h3>Understand before persuading.</h3></div><div class="bridge-diamond">◇</div><div><small>ESPAÑOL</small><h3>Comprende antes de persuadir.</h3></div></div><p class="lead">The manuals do not merely translate words. They preserve the same customer standard, coaching logic and operating intent across the team.</p>`,btn('Enter the Living Manual'));n='One standard. Two languages. No loss of meaning. The manuals preserve the same customer standard, coaching logic and operating intent across the team.'}
 if(scene==='manual'){html=shell('PROOF OF EXECUTION','The manual is alive.',`<p class="copy">Search it. Switch languages. Ask it what to do. Move between the agent, manager and objection systems without leaving the work.</p>${manualViewer()}`,btn('Add leadership judgment'));n='The manual is alive. Search it, switch languages, ask it what to do, and move between operating systems without leaving the work.'}
 if(scene==='evolve'){html=shell('LIVING MANUAL ADD-ON','Now the company can learn from Ed.',`<p class="lead">When a customer says, “I’m just looking,” what should every future representative understand?</p><textarea id="contribution" placeholder="Speak or type the principle every future representative should inherit.">${esc(state.contribution)}</textarea><div class="evolution-preview"><span>ED'S JUDGMENT</span><b>→</b><span>AGENT GUIDANCE</span><b>→</b><span>COACHING</span><b>→</b><span>QA</span><b>→</b><span>FUTURE HIRES</span></div>`,btn('Propagate my judgment','propagate','xen'));n='Now the company can learn from Ed. Tell me what every future representative should understand when a customer says, I am just looking.'}
 if(scene==='propagate'){html=shell('VISIBLE PROPAGATION','One decision. Every connected layer learns.',`<div class="propagation">${[['Agent manual','UPDATED'],['Manager coaching','INHERITED'],['Spanish guidance','SYNCHRONISED'],['Call quality standard','MEASURE ADDED'],['New-hire Academy','CERTIFICATION UPDATED'],['Executive memory','ATTRIBUTED TO ED']].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`,btn('Reveal Xen'));n='One approved decision. Every connected layer learns. The instruction is no longer trapped in the room where it was spoken.'}
 if(scene==='orchestra'){html=`<section class="scene reveal"><div class="reveal-diamond">◇</div><div class="eyebrow">THE REVEAL</div><h1>The manual was only the first instrument.</h1><p class="lead">Xen conducts the company.</p><div class="orchestra-line"><span>Purpose</span><i></i><span>Memory</span><i></i><span>People</span><i></i><span>Departments</span><i></i><span>Companies</span></div><div class="actions">${btn('Show me the enterprise','next','xen')}</div></section>`;n='The manual was only the first instrument. Xen conducts the company. Purpose, memory, people, departments and companies working as one.'}
 if(scene==='purpose'){html=shell('EXECUTIVE SYMPHONY','Every company directed toward its purpose—and yours.',`<p class="lead">Xen can give each company its own mission, memory and operating intelligence while allowing Ed to see where the entire group is aligned, drifting, blocked or ready to grow.</p><div class="enterprise-orbit"><div class="ed-core">ED<br><small>PURPOSE</small></div>${['COMPANY 01','COMPANY 02','COMPANY 03','COMPANY 04','COMPANY 05','COMPANY 24'].map((x,i)=>`<div class="orbit-company o${i}"><i></i>${x}</div>`).join('')}</div><div class="executive-question">What if all 24 companies could understand where they are going—and help each other get there?</div>`,btn('Build the Executive Summary'));n='Every company directed toward its purpose, and yours. Xen can give each company its own mission, memory and operating intelligence while you see where the entire group is aligned, drifting, blocked or ready to grow.'}
 if(scene==='close'){html=shell('EXECUTIVE SUMMARY','The BDC system is the proof. Your enterprise is the opportunity.',`<div class="summary"><div><small>WHAT XEN PROVED</small><p>A new department can inherit operating intelligence instead of starting from zero.</p></div><div><small>WHAT CHANGED TODAY</small><p>Ed's judgment became bilingual, governed infrastructure across manuals, coaching, QA and future hires.</p></div><div><small>WHAT COMES NEXT</small><p>Map one Checkmate company, connect its departments, then expand the Living Company architecture across the group.</p></div></div><blockquote>“Ed, what you have seen is not software built around a company. It is the beginning of companies capable of understanding, directing and improving themselves—together.”</blockquote><div class="seal">XEN · EXECUTIVE SYMPHONY · ${VERSION}</div>`,btn('Replay the Symphony','restart','ghost'));n='The B D C system is the proof. Your enterprise is the opportunity. What you have seen is the beginning of companies capable of understanding, directing and improving themselves together.'}
 $('#stage').innerHTML=html;bind(scene);updateChrome();$('#stage').focus({preventScroll:true});window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>speak(n),scene==='intro'?350:500);
}
function next(){if(state.scene<scenes.length-1){state.scene++;save();render()}}
function back(){if(state.scene>0){state.scene--;save();render()}}
function bind(scene){
 $('#next')?.addEventListener('click',next);$('#begin')?.addEventListener('click',()=>{state.started=true;save();next()});$('#restart')?.addEventListener('click',()=>{localStorage.removeItem(KEY);state={...defaults};render()});
 document.querySelectorAll('[data-manual]').forEach(b=>b.onclick=()=>{state.manual=b.dataset.manual;save();render()});document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{state.language=b.dataset.lang;save();render()});
 document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{const q=b.dataset.question;state.answer=q.includes('just looking')?'Acknowledge without pressure, clarify what they hope to learn, then offer the smallest useful next step.':q.includes('qualify')?'Ask about the project, timing, decision-makers and desired outcome—without making the customer feel interrogated.':'Record the objective, concern, timeframe, decision-makers and agreed follow-up.';save();render()});
 $('#manualSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.manual-line').forEach(x=>x.hidden=q&&!x.dataset.search.includes(q))});
 $('#contribution')?.addEventListener('input',e=>{state.contribution=e.target.value;save()});$('#propagate')?.addEventListener('click',()=>{state.contribution=$('#contribution').value.trim()||'Help the customer understand enough to choose the next step willingly.';save();next()});
}
$('#back').onclick=back;$('#home').onclick=()=>{state.scene=0;save();render()};$('#voice').onclick=()=>{state.voice=!state.voice;save();if(state.voice)speak('X V S British voice activated.',true);else speechSynthesis?.cancel()};
document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')back();if(e.key==='ArrowRight'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))next()});
if('speechSynthesis'in window){speechSynthesis.onvoiceschanged=()=>{pickXVSVoice();if(state.scene===0&&state.voice)speak('Good afternoon, Ed. I am Xen.',true)}}
window.addEventListener('load',()=>{pickXVSVoice();setTimeout(()=>{if(state.scene===0&&state.voice)speak('Good afternoon, Ed. I am Xen. Welcome to Executive Symphony.',true)},200)});
render();